apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: springbit
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: springbit/spring-bit-discovery
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/frontend
                    operator: In
                    values:
                      - "yes"