apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: springbit
spec:
  selector:
    app: discovery-service
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP