networks:
  internal:
    name: internal
    internal: true
    ipam:
      config:
        - subnet: 172.177.0.0/16

services:
  discovery-service:
    container_name: discovery-service
    image: springbit/spring-bit-discovery
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 8888:8888


  config-service:
    container_name: config-service
    image: springbit/spring-bit-config
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      vault-server:
        condition: service_started
    networks:
      - internal
    ports:
      - 9095:9095

  crypto-service:
    image: springbit/spring-bit-crypto
    deploy:
      resources:
        limits:
          memory: 512M
      mode: replicated
      replicas: 1
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
      mysql-server:
        condition: service_started
    networks:
      - internal
    ports:
     - 8090:8090

  gateway-service:
    container_name: gateway-service
    image: springbit/spring-bit-gateway
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
      crypto-service:
        condition: service_started
    networks:
      - internal
      - default
    ports:
      - 8080:8080

  tracing-server:
    container_name: tracing-server
    image: openzipkin/zipkin:3
    environment:
      ZIPKIN_UI_BASEPATH: /tracing/zipkin
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
     - 9411:9411

  ## Grafana / Locki / Prometheus

  grafana-server:
    container_name: grafana-server
    build: ./docker/grafana
    image: springbit/grafana-server
    environment:
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_ROOT_URL: /grafana
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 3000:3000

  loki-server:
    container_name: loki-server
    build: ./docker/loki
    image: springbit/loki-server
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 3100:3100

  prometheus-server:
    container_name: prometheus-server
    build: ./docker/prometheus
    image: springbit/prometheus-server
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --web.external-url=/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 9090:9090

    ## Vault
  vault-server:
    container_name: vault-server
    image: hashicorp/vault
    volumes:
      - ./data/vault/:/vault-data
    entrypoint: vault server -config=/vault-data/vault-server.hcl
    post_start:
      - command: /bin/sh /vault-data/unseal.sh ; rm /vault-data/unseal.sh
        user: root
    cap_add:
      - IPC_LOCK
    networks:
      - internal
    ports:
      - 8200:8200

    ## Mysql
  mysql-server:
    container_name: mysql-server
    build: ./docker/mysql
    image: springbit/mysql-server
    networks:
      - internal
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/mysql-data

