networks:
  internal:
    name: internal
    internal: true
    ipam:
      config:
        - subnet: 172.177.0.0/16

services:
  ## Secure keys
  vault-server:
    container_name: vault-server
    build: ./docker/vault
    image: springbit/vault-server
    pull_policy: never
    volumes:
      - ./data/vault/:/vault-data
    cap_add:
      - IPC_LOCK
    networks:
      - internal
    ports:
      - 8200:8200

  ## Spring profile configs
  config-service:
    container_name: config-service
    image: springbit/spring-bit-config
    pull_policy: never
    environment:
      VAULT_USER_TOKEN: ${VAULT_USER_TOKEN}
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      vault-server:
        condition: service_started
    networks:
      - internal
    ports:
      - 9095:9095

  ## Persistent model backend
  mysql-server:
    container_name: mysql-server
    build: ./docker/mysql
    image: springbit/mysql-server
    pull_policy: never
    networks:
      - internal
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/mysql-data

  ## OpenId backend
  auth-server:
    container_name: auth-server
    image: springbit/spring-bit-oidc-server
    pull_policy: never
    depends_on:
      config-service:
        condition: service_started
    networks:
      - internal
    ports:
      - 9443:9443

  discovery-service:
    container_name: discovery-service
    image: springbit/spring-bit-discovery
    pull_policy: never
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 8888:8888

  gateway-service:
    container_name: gateway-service
    image: springbit/spring-bit-gateway
    pull_policy: never
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
      crypto-service:
        condition: service_started
      auth-server:
        condition: service_started
    networks:
      - internal
      - default
    ports:
      - 8080:8080

  crypto-service:
    container_name: crypto-service
    image: springbit/spring-bit-crypto
    pull_policy: never
    deploy:
      resources:
        limits:
          memory: 512M
      mode: replicated
      replicas: 1
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
      mysql-server:
        condition: service_started
    networks:
      - internal
    ports:
     - 8090:8090



  ## Monitoring/Logging

  tracing-server:
    container_name: tracing-server
    image: openzipkin/zipkin:3
    environment:
      ZIPKIN_UI_BASEPATH: /tracing/zipkin
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
     - 9411:9411

  grafana-server:
    container_name: grafana-server
    build: ./docker/grafana
    image: springbit/grafana-server
    pull_policy: never
    environment:
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_ROOT_URL: /grafana
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 3000:3000

  loki-server:
    container_name: loki-server
    build: ./docker/loki
    image: springbit/loki-server
    pull_policy: never
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 3100:3100

  prometheus-server:
    container_name: prometheus-server
    build: ./docker/prometheus
    image: springbit/prometheus-server
    pull_policy: never
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --web.external-url=/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 9090:9090
