services:
  api-gateway:
    image: springbit/spring-bit-crypto
    container_name: crypto
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin:3
    container_name: tracing-server
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
     - 9411:9411

  ## Grafana / Locki / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
    - 3000:3000

  loki-server:
    build: ./docker/loki
    container_name: loki-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 3100:3100

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
    - 9091:9090
