networks:
  internal:
    name: internal
    internal: true

services:
  discovery-service:
    image: springbit/spring-bit-discovery
    container_name: discovery-service
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
      - default
    ports:
      - 8888:8888

  crypto-service:
    image: springbit/spring-bit-crypto
    deploy:
      resources:
        limits:
          memory: 512M
      mode: replicated
      replicas: 2
    depends_on:
      - discovery-service
    networks:
      - internal
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin:3
    container_name: tracing-server
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - internal
      - default
    ports:
     - 9411:9411

  ## Grafana / Locki / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
      - default
    ports:
    - 3000:3000

  loki-server:
    build: ./docker/loki
    container_name: loki-server
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 3100:3100

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
      - default
    ports:
    - 9091:9090
