networks:
  internal:
    name: internal
    internal: true
    ipam:
      config:
        - subnet: 172.177.0.0/16

services:
  discovery-service:
    image: springbit/spring-bit-discovery
    container_name: discovery-service
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 8888:8888


  config-service:
    image: springbit/spring-bit-config
    container_name: config-service
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 9095:9095


  crypto-service:
    image: springbit/spring-bit-crypto
    deploy:
      resources:
        limits:
          memory: 512M
      mode: replicated
      replicas: 2
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - internal
    ports:
     - 8090:8080

  gateway-service:
    image: springbit/spring-bit-gateway
    container_name: gateway-service
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      discovery-service:
        condition: service_started
      config-service:
        condition: service_started
      crypto-service:
        condition: service_started
    networks:
      - internal
      - default
    ports:
      - 8080:8080

  tracing-server:
    image: openzipkin/zipkin:3
    container_name: tracing-server
    environment:
      ZIPKIN_UI_BASEPATH: /tracing/zipkin
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
     - 9411:9411

  ## Grafana / Locki / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    environment:
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_ROOT_URL: /grafana
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 3000:3000

  loki-server:
    build: ./docker/loki
    container_name: loki-server
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
      - 3100:3100

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.route-prefix=/
      - --web.external-url=/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - internal
    ports:
    - 9090:9090
