spring:
  application:
    name: spring-bit-gateway

---
spring:
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      routes:
        - id: crypto-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/crypto/**
          filters:
            - StripPrefix=2

        - id: crypto-service-docs
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/docs/**
          filters:
            - StripPrefix=3
            - RewriteResponseHeader=Location, ^/, /api/v1/docs/

    discovery:
      enabled: false

spring-bit:
  auth:
    gateway: http://localhost:8080
    server: http://localhost:9443
    public-auth-server: localhost:9443


management:
  prometheus:
    metrics:
      export:
        enabled: false
  tracing:
    enabled:
      false

# Logging
logging.level.org.springframework: DEBUG
logging.level.org.springframework.cloud.gateway: DEBUG
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.http: DEBUG
logging.level.org.springframework.web.filter: DEBUG
logging.level.org.springframework.web.reactive.result: DEBUG
logging.level.org.springframework.security: DEBUG

# Config server loads spring-bit-config/src/main/resources/microservices/spring-bit-gateway-production.yml
