spring:
  application:
    name: spring-bit-gateway

# Logging
logging.level.org.springframework: INFO

# Config server loads spring-bit-config/src/main/resources/microservices/spring-bit-gateway-production.yml