spring:
  application:
    name: spring-bit-crypto

  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:file:./data/chains
    username: springbit
    password: dbpass
    driverClassName: org.h2.Driver


springdoc:
  swagger-ui:
    path: /ui
    url: /api/v1/docs/v3/api-docs
    config-url: /api/v1/docs/v3/api-docs/swagger-config

spring-bit:
  init-graphql: false
  bitquery:
    apitoken:

# Logging
logging.level.org.springframework: INFO

# Config server loads spring-bit-config/src/main/resources/microservices/spring-bit-crypto-production.yml