logging.level.org.springframework: INFO

spring:
  application:
    name: spring-bit-crypto
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: r2dbc:h2:file:./data/crypto
    username: springbit
    password: dbpass

springdoc:
  swagger-ui:
    path: /ui

spring-bit:
  services:
    bitquery:
      enable: true
      url: https://graphql.bitquery.io
      api-token:
    coinmarketcap:
      enable: true
      url: https://pro-api.coinmarketcap.com
      api-token: 
---
spring:
  config:
    activate:
      on-profile: default
  cloud:
    discovery:
      enabled: false

management:
  prometheus:
    metrics:
      export:
        enabled: false
  tracing:
    enabled:
      false


# Config server loads spring-bit-config/src/main/resources/microservices/spring-bit-crypto-production.yml
