server:
  port: 8090

spring:
  application:
    name: spring-bit-crypto
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "UTC"

---
spring:
  config:
    activate:
      on-profile: default
    # get secret keys from local disk - in production they are in vault-server
    additional-location: file:${user.dir}/scripts/config/config.properties

  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
  datasource:
    url: r2dbc:h2:file:./data/crypto
    username: springbit
    password: dbpass

  cloud:
    discovery:
      enabled: false

management:
  prometheus:
    metrics:
      export:
        enabled: false
  tracing:
    enabled:
      false

springdoc:
  swagger-ui:
    path: /ui

spring-bit:
  services:
    bitquery:
      enabled: false
      url: https://graphql.bitquery.io
    coinmarketcap:
      enabled: true
      url: https://pro-api.coinmarketcap.com
    web-socket-crypto:
      enabled: true
      url: 'ws/future'
    kafka:
      enabled: true
      url: localhost:9092
      topic: crypto-topic
    ml-service:
      enabled: true
      url: http://localhost:8000


logging.level.org.springframework: DEBUG
logging.level.reactor.netty.http.client: DEBUG

# Config server loads spring-bit-config/src/main/resources/microservices/spring-bit-crypto-production.yml
