apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-service
  namespace: springbit
  labels:
    app: crypto-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-service
  template:
    metadata:
      labels:
        app: crypto-service
    spec:
      containers:
      - name: crypto-service
        image: springbit/spring-bit-crypto
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "sleep 1" ]
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/backend
                    operator: In
                    values:
                      - "yes"