apiVersion: v1
kind: Service
metadata:
  name: crypto-service
  namespace: springbit
spec:
  selector:
    app: crypto-service
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
  type: ClusterIP