apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: springbit
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
        - name: nginx-ingress-controller
          image: nginx-ingress-controller:latest
          ports:
            - containerPort: 80
              hostPort: 80  # Map container's port 80 to the host's port 80
            - containerPort: 443
              hostPort: 443  # Map container's port 443 to the host's port 443
          args:
            - /nginx-ingress-controller
            - --ingress-class=nginx