apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-server
  namespace: springbit
  labels:
    app: loki-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-server
  template:
    metadata:
      labels:
        app: loki-server
    spec:
      containers:
      - name: loki-server
        image: springbit/loki-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3100
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/monitoring
                    operator: In
                    values:
                      - "yes"