apiVersion: v1
kind: Service
metadata:
  name: loki-server
  namespace: springbit
spec:
  selector:
    app: loki-server
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
  type: ClusterIP