apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: springbit
  labels:
    app: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: springbit/spring-bit-ml
        imagePullPolicy: IfNotPresent
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: springbit-secret
                key: openai-key
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/backend
                    operator: In
                    values:
                      - "yes"