apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-server
  namespace: springbit
  labels:
    app: vault-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      containers:
      - name: vault-server
        image: springbit/vault-server
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /vault-data
            name: vault-server-volume
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
        - name: vault-server-volume
          persistentVolumeClaim:
            claimName: vault-server-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/volume
                    operator: In
                    values:
                      - "yes"
      imagePullSecrets:
        - name: docker-secret