apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-server-volume
  namespace: springbit
spec:
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /hostdata/vault  # Local path in minikube node's vm
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: springbit.org/volume
              operator: In
              values:
                - "yes"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-server-volume
  namespace: springbit
spec:
  volumeName: vault-server-volume
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce  # The claim needs to be mounted as read-write by a single node
  resources:
    requests:
      storage: 50Mi