apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: springbit
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: springbit/spring-bit-gateway
        imagePullPolicy: IfNotPresent
        env:
            - name: SPRINGBIT_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: springbit-secret
                  key: public-domain
        lifecycle:
          preStop:
            exec:
              command: [ "sleep 2" ]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/frontend
                    operator: In
                    values:
                      - "yes"