apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: springbit
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: springbit/spring-bit-config
        imagePullPolicy: IfNotPresent
        env:
          - name: VAULT_USER_TOKEN
            valueFrom:
              secretKeyRef:
                name: springbit-secret
                key: vault-token
        ports:
        - containerPort: 9095
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/backend
                    operator: In
                    values:
                      - "yes"
