apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: springbit
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: springbit/spring-bit-config
        imagePullPolicy: IfNotPresent
        env:
          - name: VAULT_USER_TOKEN
            value: ${VAULT_USER_TOKEN}
        ports:
        - containerPort: 9095
