server:
  port: 9443

logging.level.org.springframework.security: debug

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          springbit-client:
            registration:
              client-id: "springbit-openid"
              client-secret: "$2a$12$3TCra0mBe6VRJ4uc9zyUEeKrNAB7VHLie0KQ9er0sS5sG7mrljHCO"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "${spring-bit.auth.gateway}/login/oauth2/code/springbit-openid"
                - "${spring-bit.auth.gateway}/authorized"
              post-logout-redirect-uris:
                - "${spring-bit.auth.gateway}/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "monitoring.read"
            require-authorization-consent: true

---
spring:
  config:
    activate:
      on-profile: default

management:
  prometheus:
    metrics:
      export:
        enabled: false
  tracing:
    enabled:
      false

spring-bit:
  auth:
    gateway: http://localhost:8080
