apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  namespace: springbit
spec:
  selector:
    app: grafana-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP