spring:
  application:
    name: spring-bit-crypto
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql

  r2dbc:
    url: r2dbc:mysql://mysql-server:3306/springbit
    username: spring-bit-user
    password: '{vault}:keys#spring-bit.db.mysql.springbit.password'
    properties.ssl: true
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m

springdoc:
  swagger-ui:
    path: /ui
    url: /api/v1/docs/v3/api-docs
    config-url: /api/v1/docs/v3/api-docs/swagger-config

# The spring-bit-crypto containers are only on the internal network
# So forward their requests through the gateway - see routes
spring-bit:
  services:
    bitquery:
      enabled: false
      url: http://gateway-service:8080/bitquery
      api-token: '{vault}:keys#spring-bit.services.bitquery.api-token'
    coinmarketcap:
      enabled: true
      url: http://gateway-service:8080/coinmarketcap
      api-token: '{vault}:keys#spring-bit.services.coinmarketcap.api-token'

# Logging
logging.level.org.springframework: ${LOG_LEVEL:INFO}
logging.level.org.springframework.security: ${LOG_LEVEL:INFO}