spring:
  application:
    name: spring-bit-auth-server
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml
    oauth2:
      authorization-server:
        issuer: ${SPRINGBIT_AUTH_DOMAIN:localhost:9443}

spring-bit:
  auth:
    gateway: ${SPRINGBIT_DOMAIN:http://localhost:8080}

# Logging
logging.level.org.springframework: ${LOG_LEVEL:INFO}
logging.level.org.springframework.security: ${LOG_LEVEL:INFO}
