spring:
  application:
    name: spring-bit-oidc-server
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml

spring-bit:
  auth:
    gateway: http://gateway-service:8080

# Logging
logging.level.org.springframework: INFO
logging.level.org.springframework.security: INFO