spring:
  application:
    name: spring-bit-crypto
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml

springdoc:
  swagger-ui:
    path: /ui
    url: /api/v1/docs/v3/api-docs
    config-url: /api/v1/docs/v3/api-docs/swagger-config