spring:
  application:
    name: spring-bit-gateway
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml

spring-bit:
  public-domain: ${SPRINGBIT_DOMAIN:http://localhost:8080}

  services:
    crypto-service:
      enabled: true
      url: lb://spring-bit-crypto
    discovery-service:
      enabled: true
      url: http://discovery-service:8888
    tracing-server:
      enabled: true
      url: http://tracing-server:9411
    grafana-server:
      enabled: true
      url: http://grafana-server:3000
    prometheus-server:
      enabled: true
      url: http://prometheus-server:9090
    keycloak-server:
      enabled: true
      url: http://keycloak-server:9080
    bitquery:
      enabled: false
      url: https://graphql.bitquery.io
    coinmarketcap:
      enabled: true
      url: https://pro-api.coinmarketcap.com

  auth:
    github:
      client-id: '{vault}:keys#spring-bit.auth.github.client-id'
      client-secret: '{vault}:keys#spring-bit.auth.github.client-secret'
    facebook:
      client-id: '{vault}:keys#spring-bit.auth.facebook.client-id'
      client-secret: '{vault}:keys#spring-bit.auth.facebook.client-secret'
    keycloak:
      client-secret: '{vault}:keys#spring-bit.auth.keycloak.client-secret'

# Logging
logging.level.org.springframework: ${LOG_LEVEL:INFO}
logging.level.org.springframework.security: ${LOG_LEVEL:INFO}
logging.level.org.springframework.boot.autoconfigure: ERROR
