spring:
  application:
    name: spring-bit-gateway
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml

  cloud:
    gateway:
      routes:
        - id: crypto-service
          uri: lb://spring-bit-crypto
          predicates:
            - Path=/api/v1/crypto/**
          filters:
            - StripPrefix=2

        - id: crypto-service-docs
          uri: lb://spring-bit-crypto
          predicates:
            - Path=/api/v1/docs/**
          filters:
            - StripPrefix=3
            - RewriteResponseHeader=Location, ^/, /api/v1/docs/

        - id: discovery
          uri: http://discovery-service:8888
          predicates:
            - Path=/discovery/**
          filters:
            - StripPrefix=1
        - id: discovery-res
          uri: http://discovery-service:8888
          predicates:
            - Path=/eureka/**

        - id: tracing
          uri: http://tracing-server:9411
          predicates:
            - Path=/tracing/**
          filters:
            - StripPrefix=1
            - RewriteResponseHeader=Location, /zipkin, /tracing/zipkin

        - id: grafana
          uri: http://grafana-server:3000
          predicates:
            - Path=/grafana/**
          filters:
            - SetRequestHostHeader=localhost:8080

        - id: prometheus
          uri: http://prometheus-server:9090
          predicates:
            - Path=/prometheus/**
          filters:
            - StripPrefix=1