spring:
  application:
    name: spring-bit-crypto
  config:
    activate:
      on-profile: production
    import:
      - classpath:microservices/common/monitoring.yml
      - classpath:microservices/common/discovery.yml
      - classpath:microservices/common/logging.yml
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql

  r2dbc:
    url: r2dbc:mysql://mysql-server:3306/springbit
    username: spring-bit-user
    password: spring-bit-mysql
    #'{vault}:keys#mysql.password'
    ssl: true
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  datasource:
    ssl: true

springdoc:
  swagger-ui:
    path: /ui
    url: /api/v1/docs/v3/api-docs
    config-url: /api/v1/docs/v3/api-docs/swagger-config

# The spring-bit-crypto containers are only on the internal network
# So forward their requests through the gateway - see routes
spring-bit:
  services:
    bitquery:
      enable: false
      url: http://gateway-service:8080/bitquery
      api-token: '{vault}:keys#bitquery.api-token'
    coinmarketcap:
      enable: true
      url: http://gateway-service:8080/coinmarketcap
      api-token: '{vault}:keys#coinmarketcap.api-token'
