apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: springbit
spec:
  selector:
    app: auth-server
  ports:
  - protocol: TCP
    port: 9443
    targetPort: 9443
  type: ClusterIP