# Promtail config
server:
  disable: true

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki-server:3100/loki/api/v1/push

scrape_configs:
  - job_name: ml-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ml
          shipper: promtail
          __path__: /var/log/springbit/*.log
