apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-server:9090
  isDefault: true
  editable: true

- name: Loki
  type: loki
  access: proxy
  url: http://loki-server:3100
  basicAuth: false
  isDefault: false
  editable: true

- name: Zipkin
  type: zipkin
  access: proxy
  url: http://tracing-server:9411
  basicAuth: false
  isDefault: false
  editable: true
  jsonData:
    tracesToLogsV2:
      datasourceUid: 'Loki'
      spanStartTimeShift: '1h'
      spanEndTimeShift: '-1h'
    tracesToMetrics:
      datasourceUid: 'Prometheus'
      spanStartTimeShift: '1h'
      spanEndTimeShift: '-1h'