apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: springbit
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: springbit/mysql-server
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mysql-data
            name: mysql-server-volume
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
        - name: mysql-server-volume
          persistentVolumeClaim:
            claimName: mysql-server-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/volume
                    operator: In
                    values:
                      - "yes"
