apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: springbit
spec:
  selector:
    app: kafka-server
  ports:
    - name: kafka-plaintext
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
