apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: springbit
spec:
  selector:
    app: kafka-server
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
