apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: springbit
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus-server
        image: springbit/prometheus-server
        imagePullPolicy: IfNotPresent
        args: [ "--config.file=/etc/prometheus/prometheus.yml", "--web.route-prefix=/",  "--web.external-url=/prometheus"]
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: springbit.org/monitoring
                    operator: In
                    values:
                      - "yes"